// src/core/pr/commits.ts
// Track A — commit message slop detection.
// Pure function. Flags messages that look right but say nothing:
//   - generic verbs with no object ("update", "fix", "changes")
//   - WIP / "address comments" / "minor fixes" filler
//   - messages that just echo a filename
//   - autogenerated merge/bump noise is NOT slop (it's legitimately mechanical)

import type { CommitVerdict } from './types.js'

const GENERIC_ONLY_RE =
  /^(?:update|updates|fix|fixes|fixed|changes?|edit|edits|misc|stuff|wip|work in progress|minor (?:fix(?:es)?|changes?|updates?)|address(?:ed|ing)? (?:comments?|feedback|review)|cleanup|clean up|refactor|tweak|tweaks|patch|done|final|test|tests|temp|asdf|.)\.?$/i

const GENERIC_LEAD_RE =
  /^(?:update|fix|change|edit|refactor|improve|tweak)\s+(?:the\s+)?(?:code|files?|stuff|things?)\.?$/i

// Mechanical-but-legit messages we should NOT flag.
const MECHANICAL_RE = /^(?:merge\b|revert\b|bump\b|release\b|v?\d+\.\d+\.\d+\b|chore\(deps\))/i

export function assessCommit(message: string): CommitVerdict {
  const firstLine = (message ?? '').split('\n')[0]?.trim() ?? ''
  const reasons: string[] = []

  if (firstLine.length === 0) {
    return { message: firstLine, isSlop: true, reasons: ['empty commit message'] }
  }
  if (MECHANICAL_RE.test(firstLine)) {
    return { message: firstLine, isSlop: false, reasons: [] }
  }

  const wordCount = firstLine.split(/\s+/).filter(Boolean).length

  if (GENERIC_ONLY_RE.test(firstLine)) {
    reasons.push('generic message with no specific subject')
  }
  if (GENERIC_LEAD_RE.test(firstLine)) {
    reasons.push('describes the action but not what or why')
  }
  if (wordCount <= 2 && !/#\d+/.test(firstLine)) {
    reasons.push('too short to convey intent')
  }

  return { message: firstLine, isSlop: reasons.length > 0, reasons }
}

export function assessCommits(messages: string[]): CommitVerdict[] {
  return messages.map(assessCommit)
}
